### ISSUE TITLE
LandmarksEndpoint {     "landmarks": 

### ISSUE THREAD

**Issue by janbildsoehansen** [M-I-N/Landmarks#1]
Hey im new to swiftui and came across your build
and was wondering if I can remove this bracket in the end json file or chance the "name" of the "landmarks"..???:

{
    "landmarks": 

so you only have it like this:
[
    {
        "name": "Turtle Rock",
        "category": "Rivers",
        "city": "Twentynine Palms",
        "state": "California",
        "id": 1001,
        "isFeatured": true,
        "isFavorite": true,
        "park": "Joshua Tree National Park",
        "coordinates": {
            "longitude": -116.166868,
            "latitude": 34.011286
        },
        "imageName": "turtlerock"
    },
    {
        "name": "Silver Salmon Creek",
        "category": "Lakes",
        "city": "Port Alsworth",
        "state": "Alaska",
        "id": 1002,
        "isFeatured": false,
        "isFavorite": false,
        "park": "Lake Clark National Park and Preserve",
        "coordinates": {
            "longitude": -152.665167,
            "latitude": 59.980167
        },
        "imageName": "silversalmoncreek"
    },
    {
        "name": "Chilkoot Trail",
        "category": "Mountains",
        "city": "Skagway",
        "state": "Alaska",
        "id": 1003,
        "isFeatured": false,
        "isFavorite": true,
        "park": "Klondike Gold Rush National Historical Park",
        "coordinates": {
            "longitude": -135.334571,
            "latitude": 59.560551
        },
        "imageName": "chilkoottrail"
    },
    {
        "name": "St. Mary Lake",
        "category": "Lakes",
        "city": "Browning",
        "state": "Montana",
        "id": 1004,
        "isFeatured": true,
        "isFavorite": true,
        "park": "Glacier National Park",
        "coordinates": {
            "longitude": -113.536248,
            "latitude": 48.69423
        },
        "imageName": "stmarylake"
    },
    {
        "name": "Twin Lake",
        "category": "Lakes",
        "city": "Twin Lakes",
        "state": "Alaska",
        "id": 1005,
        "isFeatured": false,
        "isFavorite": false,
        "park": "Lake Clark National Park and Preserve",
        "coordinates": {
            "longitude": -153.849883,
            "latitude": 60.641684
        },
        "imageName": "twinlake"
    },
    {
        "name": "Lake McDonald",
        "category": "Mountains",
        "city": "West Glacier",
        "state": "Montana",
        "id": 1006,
        "isFeatured": false,
        "isFavorite": false,
        "park": "Glacier National Park",
        "coordinates": {
            "longitude": -113.934831,
            "latitude": 48.56002
        },
        "imageName": "lakemcdonald"
    },
    {
        "name": "Charley Rivers",
        "category": "Rivers",
        "city": "Eaking",
        "state": "Alaska",
        "id": 1007,
        "isFeatured": true,
        "isFavorite": false,
        "park": "Charley Rivers National Preserve",
        "coordinates": {
            "longitude": -143.122586,
            "latitude": 65.350021
        },
        "imageName": "charleyrivers",
    },
    {
        "name": "Icy Bay",
        "category": "Mountains",
        "city": "Icy Bay",
        "state": "Alaska",
        "id": 1008,
        "isFeatured": false,
        "isFavorite": false,
        "park": "Wrangell-St. Elias National Park and Preserve",
        "coordinates": {
            "longitude": -141.518167,
            "latitude": 60.089917
        },
        "imageName": "icybay"
    },
    {
        "name": "Rainbow Lake",
        "category": "Lakes",
        "city": "Willow",
        "state": "Alaska",
        "id": 1009,
        "isFeatured": false,
        "isFavorite": false,
        "park": "State Recreation Area",
        "coordinates": {
            "longitude": -150.086103,
            "latitude": 61.694334
        },
        "imageName": "rainbowlake"
    },
    {
        "name": "Hidden Lake",
        "category": "Lakes",
        "city": "Newhalem",
        "state": "Washington",
        "id": 1010,
        "isFeatured": false,
        "isFavorite": false,
        "park": "North Cascades National Park",
        "coordinates": {
            "longitude": -121.17799,
            "latitude": 48.495442
        },
        "imageName": "hiddenlake"
    },
    {
        "name": "Chincoteague",
        "category": "Rivers",
        "city": "Chincoteague",
        "state": "Virginia",
        "id": 1011,
        "isFeatured": false,
        "isFavorite": false,
        "park": "Chincoteague National Wildlife Refuge",
        "coordinates": {
            "longitude": -75.383212,
            "latitude": 37.91531
        },
        "imageName": "chincoteague"
    },
    {
        "name": "Lake Umbagog",
        "category": "Lakes",
        "city": "Errol",
        "state": "New Hampshire",
        "id": 1012,
        "isFeatured": true,
        "isFavorite": false,
        "park": "Umbagog National Wildlife Refuge",
        "coordinates": {
            "longitude": -71.056816,
            "latitude": 44.747408
        },
        "imageName": "umbagog"
    }
]

best regards

**Comment by M-I-N** [comment]
Hi @janbildsoehansen , yes you can change the `JSON` structure as your need. But keep in mind that as soon as you change the structure of the `JSON` you are likely to break your implementation in the code. This is because you obviously encode/decode the external objects, in this case the **Landmarks.json**. 

So, what you are proposing is you want to change the json from `[String : Any]` that is a dictionary to `[Any]` that is an array. And json supports both of them. 

But you also need to be cautious here: 
https://github.com/M-I-N/Landmarks/blob/26e23269021ef507d27f3e77e9b4b0ec5b12f507/Landmarks/Client/LandmarksClient.swift#L23

because you should no longer try to decode `LandmarksResponse` but `[Landmark]`

and this struct can completely be removed: 
https://github.com/M-I-N/Landmarks/blob/26e23269021ef507d27f3e77e9b4b0ec5b12f507/Landmarks/Client/LandmarksClient.swift#L35

---

I hope you can handle the mentioned cautious area on your own. If not, I would recommend you reading on `Codable` protocol and related stuffs with json encoding/decoding with `Codable`.

**Comment by janbildsoehansen** [comment]
I got it to work by just change landmark to data :

struct LandmarksResponse: Decodable {
    let data: [Landmark]
}

thanks
